### ISSUE TITLE
Step Sequencer not mapping steps to pads correctly

### ISSUE THREAD

**Issue by fasho021** [forgery810/fl-studio-presonus-atom-sq#5]
Hello Forgery810, 

First let me say thank you for all the great work you have done with building this script. Scripts with FL studio is a fairly new concept to me so please excuse any ignorance on my part. I recently installed your script to my atom sq in FL Studio Mac version, however... the step sequencer and the pads do not map correctly. When I select the first 1-12 pads, they do not arm the desired steps. But instead, when I press the first pad, it arms the 13th step and so on. in mapping for dummies version 😁 how can I get the step sequencer to map properly to the pads in FL Mac version? Also, I followed your channel this week. can you do more videos on using the atom sq in FL Studio, with your script? That is one of the reasons I purchased the SQ, I was looking for a controller I could use in both Studio One and FL as I travel between the two daws frequently. 

Thanks in advance for any gems you drop on this post. 

Sho

**Comment by forgery810** [comment]
Hi Sho,

Most likely the issue you are having has to do with how you have the SQ setup. If you push the "Inst" button, the settings should read as follows:

Pads - Continuous
Transpose - 0
Octave - 0
Scale - Chrom
Root - C
Velocity - All or Full

Under "Editor" Pad 1 should read C1, 2 should be C#1 and go up from there.

The script relies on these settings staying the same, so unfortunately you have to leave them this way while you use FL. You'll have to reset it this way every time you move back from Studio One.

Let me know if this solves the issue or not. 

I'll try to get around to doing another video for it. There are a couple features I don't cover in the one I have up.

Thanks

**Comment by fasho021** [comment]
You are a Genius! Thank you Forgery! 

Ill be on the lookout for any new videos!

**Comment by forgery810** [comment]
Glad you got it working. Let me know if you have any other issues or
feature requests.
